name: ci.yml
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: rerun
        with:
          test: 'test'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.rerun.outputs.test }}
